# Generated by Django 2.0.13 on 2019-04-16 23:55

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalesRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sales_time', models.DateField(help_text='销售日期', verbose_name='销售日期')),
                ('create_time', models.DateTimeField(default=datetime.datetime.now, help_text='创建时间', verbose_name='创建时间')),
                ('retail_sales', models.IntegerField(blank=True, default=0, help_text='零售销量', null=True, verbose_name='零售销量')),
                ('retail_price', models.FloatField(blank=True, default=0, help_text='实际零售金额', null=True, verbose_name='实际零售金额')),
                ('project_sales', models.IntegerField(blank=True, default=0, help_text='工程销量', null=True, verbose_name='工程销量')),
                ('project_price', models.FloatField(blank=True, default=0, help_text='实际工程金额', null=True, verbose_name='实际工程金额')),
                ('wholesale_sales', models.IntegerField(blank=True, default=0, help_text='批发销量', null=True, verbose_name='批发销量')),
                ('wholesale_price', models.FloatField(blank=True, default=0, help_text='实际批发金额', null=True, verbose_name='实际批发金额')),
                ('online_sales', models.IntegerField(blank=True, default=0, help_text='电商销量', null=True, verbose_name='电商销量')),
                ('online_price', models.FloatField(blank=True, default=0, help_text='实际电商金额', null=True, verbose_name='实际电商金额')),
                ('src', models.CharField(blank=True, default='无', help_text='数据来源', max_length=100, null=True, verbose_name='数据来源')),
                ('extra', models.TextField(blank=True, help_text='拓展字段', null=True, verbose_name='拓展字段')),
                ('business', models.ForeignKey(help_text='商家代码', on_delete=django.db.models.deletion.CASCADE, to='common.Business', verbose_name='商家代码')),
                ('product', models.ForeignKey(help_text='产品型号', on_delete=django.db.models.deletion.CASCADE, to='common.Product', verbose_name='产品型号')),
                ('store', models.ForeignKey(help_text='门店代码', on_delete=django.db.models.deletion.CASCADE, to='common.Store', verbose_name='门店代码')),
            ],
            options={
                'verbose_name': '销量记录',
                'verbose_name_plural': '销量记录',
                'db_table': 'tb_sales_record',
            },
        ),
    ]
