# Generated by Django 2.0.13 on 2019-05-05 00:02

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='salesrecord',
            old_name='sales_time',
            new_name='sales_date',
        ),
        migrations.AlterField(
            model_name='salesrecord',
            name='business',
            field=models.ForeignKey(help_text='商家代码', on_delete=django.db.models.deletion.CASCADE, related_name='sales_business', to='common.Business', verbose_name='商家代码'),
        ),
        migrations.AlterField(
            model_name='salesrecord',
            name='create_time',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now, help_text='创建时间', null=True, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='salesrecord',
            name='product',
            field=models.ForeignKey(help_text='产品型号', on_delete=django.db.models.deletion.CASCADE, related_name='sales_product', to='common.Product', verbose_name='产品型号'),
        ),
        migrations.AlterField(
            model_name='salesrecord',
            name='store',
            field=models.ForeignKey(help_text='门店代码', on_delete=django.db.models.deletion.CASCADE, related_name='sales_store', to='common.Store', verbose_name='门店代码'),
        ),
    ]
