# Generated by Django 2.0.13 on 2019-04-17 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salesrecord',
            name='src',
        ),
        migrations.AddField(
            model_name='salesrecord',
            name='data_src',
            field=models.CharField(blank=True, default='', help_text='数据来源', max_length=100, null=True, verbose_name='数据来源'),
        ),
    ]
