# Generated by Django 2.0.13 on 2019-05-05 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0002_auto_20190505_0002'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesrecord',
            name='online_price',
            field=models.FloatField(blank=True, default=0, help_text='实际电商金额', verbose_name='实际电商金额'),
        ),
        migrations.AlterField(
            model_name='salesrecord',
            name='online_sales',
            field=models.IntegerField(blank=True, default=0, help_text='电商销量', verbose_name='电商销量'),
        ),
        migrations.AlterField(
            model_name='salesrecord',
            name='project_price',
            field=models.FloatField(blank=True, default=0, help_text='实际工程金额', verbose_name='实际工程金额'),
        ),
        migrations.AlterField(
            model_name='salesrecord',
            name='project_sales',
            field=models.IntegerField(blank=True, default=0, help_text='工程销量', verbose_name='工程销量'),
        ),
        migrations.AlterField(
            model_name='salesrecord',
            name='retail_price',
            field=models.FloatField(blank=True, default=0, help_text='实际零售金额', verbose_name='实际零售金额'),
        ),
        migrations.AlterField(
            model_name='salesrecord',
            name='retail_sales',
            field=models.IntegerField(blank=True, default=0, help_text='零售销量', verbose_name='零售销量'),
        ),
        migrations.AlterField(
            model_name='salesrecord',
            name='wholesale_price',
            field=models.FloatField(blank=True, default=0, help_text='实际批发金额', verbose_name='实际批发金额'),
        ),
        migrations.AlterField(
            model_name='salesrecord',
            name='wholesale_sales',
            field=models.IntegerField(blank=True, default=0, help_text='批发销量', verbose_name='批发销量'),
        ),
    ]
