# Generated by Django 2.0.13 on 2019-04-16 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0002_auto_20190414_2036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesrecord',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
