# Generated by Django 2.0.13 on 2019-04-16 23:55

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_date', models.DateField(help_text='发货日期', verbose_name='发货日期')),
                ('order_num', models.CharField(help_text='订单号', max_length=20, verbose_name='订单号')),
                ('count', models.IntegerField(help_text='要货数量', verbose_name='要货数量')),
                ('price', models.FloatField(help_text='供价', verbose_name='供价')),
                ('total_price', models.FloatField(help_text='供货总价', verbose_name='供货总价')),
                ('remarks', models.TextField(blank=True, default='', help_text='备注', null=True, verbose_name='备注')),
                ('create_time', models.DateTimeField(default=datetime.datetime.now, help_text='创建时间', verbose_name='创建时间')),
                ('business', models.ForeignKey(help_text='商家', on_delete=django.db.models.deletion.CASCADE, to='common.Business', verbose_name='商家')),
                ('product', models.ForeignKey(help_text='产品', on_delete=django.db.models.deletion.CASCADE, to='common.Product', verbose_name='产品')),
            ],
            options={
                'verbose_name': '供货记录',
                'verbose_name_plural': '供货记录',
                'db_table': 'tb_order_record',
            },
        ),
    ]
