# Generated by Django 2.0.13 on 2019-05-05 00:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supply', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplyrecord',
            name='create_time',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now, help_text='创建时间', null=True, verbose_name='创建时间'),
        ),
    ]
