# Generated by Django 2.0.13 on 2019-04-16 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supply', '0002_auto_20190414_2036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderrecord',
            name='id',
            field=models.IntegerField(auto_created=True, help_text='id', primary_key=True, serialize=False, verbose_name='id'),
        ),
    ]
