# Generated by Django 2.0.13 on 2019-04-11 18:48

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderRecord',
            fields=[
                ('id', models.IntegerField(help_text='id', primary_key=True, serialize=False, verbose_name='id')),
                ('order_date', models.DateField(help_text='订单日期', verbose_name='订单日期')),
                ('order_num', models.CharField(help_text='订单号', max_length=20, verbose_name='订单号')),
                ('count', models.IntegerField(help_text='供货数量', verbose_name='供货数量')),
                ('price', models.FloatField(help_text='供供货单价', verbose_name='供货单价')),
                ('total_price', models.FloatField(help_text='供货总价', verbose_name='供货总价')),
                ('create_time', models.DateTimeField(default=datetime.datetime.now, help_text='创建时间', verbose_name='创建时间')),
                ('business', models.ForeignKey(help_text='商家名称', on_delete=django.db.models.deletion.PROTECT, to='common.Business', verbose_name='商家名称')),
                ('product', models.ForeignKey(help_text='产品', on_delete=django.db.models.deletion.PROTECT, to='common.Product', verbose_name='产品')),
            ],
            options={
                'verbose_name': '供货记录',
                'verbose_name_plural': '供货记录',
                'db_table': 'tb_order_record',
            },
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock_count', models.IntegerField(help_text='库存数', verbose_name='库存数')),
                ('create_time', models.DateTimeField(default=datetime.datetime.now, help_text='创建时间', verbose_name='创建时间')),
                ('modify_time', models.DateTimeField(default=datetime.datetime.now, help_text='更新时间', verbose_name='更新时间')),
                ('business', models.ForeignKey(help_text='商家名称', on_delete=django.db.models.deletion.PROTECT, to='common.Business', verbose_name='商家名称')),
                ('product', models.ForeignKey(help_text='产品', on_delete=django.db.models.deletion.PROTECT, to='common.Product', verbose_name='产品')),
                ('store', models.ForeignKey(help_text='门店名称', on_delete=django.db.models.deletion.PROTECT, to='common.Store', verbose_name='门店名称')),
            ],
            options={
                'verbose_name': '库存',
                'verbose_name_plural': '库存',
                'db_table': 'tb_stock',
            },
        ),
    ]
