# Generated by Django 2.0.13 on 2019-04-16 23:55

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock_count', models.IntegerField(help_text='库存数', verbose_name='库存数')),
                ('remarks', models.TextField(blank=True, default='', help_text='备注', null=True, verbose_name='备注')),
                ('is_init', models.BooleanField(default=False, help_text='是否是初始导入的数据', verbose_name='初始数据')),
                ('create_time', models.DateTimeField(default=datetime.datetime.now, help_text='创建时间', verbose_name='创建时间')),
                ('modify_time', models.DateTimeField(default=datetime.datetime.now, help_text='更新时间', verbose_name='更新时间')),
                ('business', models.ForeignKey(help_text='商家名称', on_delete=django.db.models.deletion.CASCADE, to='common.Business', verbose_name='商家名称')),
                ('product', models.ForeignKey(help_text='产品', on_delete=django.db.models.deletion.CASCADE, to='common.Product', verbose_name='产品')),
            ],
            options={
                'verbose_name': '库存',
                'verbose_name_plural': '库存',
                'db_table': 'tb_stock',
            },
        ),
        migrations.CreateModel(
            name='StockHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock_count', models.IntegerField(help_text='库存数', verbose_name='库存数')),
                ('is_init', models.BooleanField(default=False, help_text='是否是初始导入的数据', verbose_name='初始数据')),
                ('record_time', models.DateTimeField(default=datetime.datetime.now, help_text='创建时间', verbose_name='创建时间')),
                ('create_time', models.DateTimeField(default=datetime.datetime.now, help_text='创建时间', verbose_name='创建时间')),
                ('business', models.ForeignKey(help_text='商家名称', on_delete=django.db.models.deletion.CASCADE, to='common.Business', verbose_name='商家名称')),
                ('product', models.ForeignKey(help_text='产品', on_delete=django.db.models.deletion.CASCADE, to='common.Product', verbose_name='产品')),
            ],
            options={
                'verbose_name': '历史库存',
                'verbose_name_plural': '历史库存',
                'db_table': 'tb_stock_history',
            },
        ),
    ]
