# Generated by Django 2.0.13 on 2019-05-05 00:02

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='business',
            field=models.ForeignKey(help_text='商家名称', on_delete=django.db.models.deletion.CASCADE, related_name='stock_business', to='common.Business', verbose_name='商家名称'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='create_time',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now, help_text='创建时间', null=True, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='modify_time',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now, help_text='更新时间', null=True, verbose_name='更新时间'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='product',
            field=models.ForeignKey(help_text='产品', on_delete=django.db.models.deletion.CASCADE, related_name='stock_product', to='common.Product', verbose_name='产品'),
        ),
        migrations.AlterField(
            model_name='stockhistory',
            name='create_time',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now, help_text='创建时间', null=True, verbose_name='创建时间'),
        ),
    ]
