# Generated by Django 2.0.13 on 2019-04-13 07:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderrecord',
            name='business',
        ),
        migrations.RemoveField(
            model_name='orderrecord',
            name='product',
        ),
        migrations.DeleteModel(
            name='OrderRecord',
        ),
    ]
