# Generated by Django 2.0.13 on 2019-04-14 19:37

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Business',
            fields=[
                ('business_code', models.CharField(help_text='商家代码', max_length=10, primary_key=True, serialize=False, unique=True, verbose_name='商家代码')),
                ('business_name', models.CharField(help_text='商家名称', max_length=100, unique=True, verbose_name='商家名称')),
                ('office', models.CharField(blank=True, default='', help_text='办事处', max_length=50, null=True, verbose_name='办事处')),
                ('company_type', models.CharField(blank=True, default='', help_text='公司分类', max_length=50, null=True, verbose_name='公司分类')),
                ('is_delete', models.BooleanField(default=False, help_text='是否删除', verbose_name='是否删除')),
                ('is_init', models.BooleanField(default=False, help_text='是否是初始导入的数据', verbose_name='初始数据')),
                ('create_time', models.DateTimeField(default=datetime.datetime.now, help_text='创建时间', verbose_name='创建时间')),
                ('modify_time', models.DateTimeField(default=datetime.datetime.now, help_text='修改时间', verbose_name='修改时间')),
            ],
            options={
                'verbose_name': '商家',
                'verbose_name_plural': '商家',
                'db_table': 'tb_business',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('product_name', models.CharField(blank=True, help_text='产品名称', max_length=100, null=True, unique=True, verbose_name='产品名称')),
                ('product_mod', models.CharField(help_text='产品型号', max_length=100, primary_key=True, serialize=False, unique=True, verbose_name='产品型号')),
                ('specifications', models.TextField(blank=True, default='', help_text='规格', null=True, verbose_name='规格')),
                ('is_delete', models.BooleanField(default=False, help_text='是否删除', verbose_name='是否删除')),
                ('is_init', models.BooleanField(default=False, help_text='是否是初始导入的数据', verbose_name='初始数据')),
                ('create_time', models.DateTimeField(default=datetime.datetime.now, help_text='创建时间', verbose_name='创建时间')),
                ('modify_time', models.DateTimeField(default=datetime.datetime.now, help_text='更新时间', verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '产品',
                'verbose_name_plural': '产品',
                'db_table': 'tb_product',
            },
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.IntegerField(auto_created=True, default=1, help_text='id', primary_key=True, serialize=False, verbose_name='id')),
                ('store_name', models.CharField(help_text='门店名称', max_length=100, unique=True, verbose_name='门店名称')),
                ('is_delete', models.BooleanField(default=False, help_text='是否删除', verbose_name='是否删除')),
                ('create_time', models.DateTimeField(default=datetime.datetime.now, help_text='创建时间', verbose_name='创建时间')),
                ('modify_time', models.DateTimeField(default=datetime.datetime.now, help_text='更新时间', verbose_name='更新时间')),
                ('business', models.ForeignKey(help_text='商家', on_delete=django.db.models.deletion.CASCADE, to='common.Business', verbose_name='商家')),
            ],
            options={
                'verbose_name': '门店',
                'verbose_name_plural': '门店',
                'db_table': 'tb_store',
            },
        ),
    ]
