# Generated by Django 2.0.13 on 2019-04-11 19:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='create_time',
            field=models.DateTimeField(default=datetime.datetime.now, help_text='创建时间', verbose_name='创建时间'),
        ),
        migrations.AddField(
            model_name='product',
            name='modify_time',
            field=models.DateTimeField(default=datetime.datetime.now, help_text='更新时间', verbose_name='更新时间'),
        ),
    ]
