# Generated by Django 2.0.13 on 2019-05-05 00:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='create_time',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now, help_text='创建时间', null=True, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='business',
            name='modify_time',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now, help_text='修改时间', null=True, verbose_name='修改时间'),
        ),
        migrations.AlterField(
            model_name='product',
            name='create_time',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now, help_text='创建时间', null=True, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='product',
            name='modify_time',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now, help_text='更新时间', null=True, verbose_name='更新时间'),
        ),
        migrations.AlterField(
            model_name='store',
            name='create_time',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now, help_text='创建时间', null=True, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='store',
            name='modify_time',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now, help_text='更新时间', null=True, verbose_name='更新时间'),
        ),
    ]
