# Generated by Django 2.0.13 on 2019-04-13 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_auto_20190411_1927'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='type',
            field=models.CharField(help_text='公司分类', max_length=50, verbose_name='公司分类'),
        ),
    ]
