# Generated by Django 2.0.13 on 2019-05-05 21:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_auto_20190505_0002'),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_path', models.FilePathField(verbose_name='上传文件路径')),
                ('create_time', models.DateTimeField(blank=True, default=datetime.datetime.now, help_text='创建时间', null=True, verbose_name='创建时间')),
            ],
        ),
    ]
