# Generated by Django 2.0.13 on 2019-05-05 21:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0004_auto_20190505_2149'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='uploadfile',
            options={'verbose_name': '上传文件', 'verbose_name_plural': '上传文件'},
        ),
        migrations.AlterModelTable(
            name='uploadfile',
            table='tb_upload_file',
        ),
    ]
