# Generated by Django 2.0.13 on 2019-05-06 00:27

import apps.common.models
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0005_auto_20190505_2151'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadfile',
            name='create_time',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now, help_text='创建时间', verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='uploadfile',
            name='file_path',
            field=models.FileField(help_text='上传文件路径', upload_to=apps.common.models.file_directory_path, verbose_name='上传文件路径'),
        ),
    ]
